### ISSUE TITLE
bug: /src/Cache.cpp:280:12: error: ‘UINT_MAX’ was not declared in this scope

### ISSUE THREAD

**Issue by moon548834** [hehao98/RISCV-Simulator#1]
Hi hehao98! I cloned your project on ubuntu16. When I tried to execute 
make
a error goes like the title. And I rewrote that line like this :
return uint32_t(-1);
Then I can successfully execute the make command, and I ran your example which is  
./Simulator ../riscv-elf/ackermann.riscv
Finally, I got the result just like your's. I don't know how you ran the project because I grep that marco but couldn't find the definition in the Makefile or *.h *.cpp. 
Anyway, Thanks your work, it helps me a lot!

**Comment by hehao98** [comment]
Thank you for your feedback! I have only tested this project on Mac OS X and not on Ubuntu, so l might have used some Apple Clang features by accident. I will fix this right now.
