### ISSUE TITLE
Mistake when handling 2 consecutive branch instruction

### ISSUE THREAD

**Issue by ToneyZZZ** [hehao98/RISCV-Simulator#4]
Hello, sorry to interupt you after such a long time.

I am a student taking Computer Architecture class CSC3050 in CUHKSZ, one of our assignment involves reproducing the pipeline implementation in this simulator project. After reading codes in your project, my classmate and I find a mistake in decode stage of the pipeline.

The decode stage save branch destination address directly under class `Simulator`, it may handle 2 consecutive branch instruction wrongly. I've pulled a request with fixed version. 

The detail is as follow:

The mistake appears when simulating 2 consecutive branch instruction and the first instruction is predicted wrongly, the simulator will jump to `rd` record in the 2nd instrution instead of the first instruction.
for example:
```
bne a0, a1, dest1
bne a0, a2, dest2
```
when predictor predict not to jump but `a0` = `a1`, the simulator will actually jump to `dest2` instead of `dest1`.

We believe this mistake is caused by the member `Simulator->anotherPC` and `Simulator->predictedPC`, they are saved directly under `Simulator` class, therefore behaved as a global variable during the simulation. 

So at the loop when the first branch instruction is to be executed, decode stage deals with the second branch instruction update pair `Simulator->anotherPC`, `Simulator->predictedPC` to it's current instrution `rd`, which contains `dest2` and covers `dest1`, so after that, at execute stage, `Simulator->anotherPC` no longer saves correct destination `dest1` anymore.

The change of fixed version is as follow:
- Shift member `Simulator->anotherPC` `Simulator->predictedPC` into `DReg` struct in `simulator.h`
- Change all part in `simulator.cpp` involves these two addresses (e.g. `this->anotherPC` to `this->dRegNew->anotherPC` at decode stage), pass this address through stage registers. 

We also make a test case that will show different output, it's attached below. 
[test-doublebranch.zip](https://github.com/hehao98/RISCV-Simulator/files/14965705/test-doublebranch.zip)
The test executable file `temp.riscv` is compiled by the file `temp.c` with RV32I instruction set, if simulated correctly, the output will be `1453`, but the simulator actually outputs `1644` when choosing `NT` (always not taken) as predict strategy.

**Comment by hehao98** [comment]
Thank you for your detailed bug report and PR! Looks good to me
